package Paneles;

import java.awt.event.ActionListener;

/**
 * Bases de datos 750006C-01
 * Proyecto de curso
 * Profesor: Oswaldo Solarte
 * 
 * Archivo: PanelAdministrar.java
 * Licencia: GNU-GPL
 * @version 1.0
 * 
 * @author Alejandro Guerrero Cano      (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">} 
 * @author Juan David Loaiza Santiago   (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">} 
 * @author Juan Sebastian Muñoz Rojas   (202177436-3743) {@literal <"juan.munoz.rojas@correounivalle.edu.co">} 
 * 
 */

public class PanelAdministrar extends javax.swing.JPanel {

    /** Creates new form PanelAdministrar */
    public PanelAdministrar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrolleable = new javax.swing.JScrollPane();
        subpanel_scrolleable = new javax.swing.JPanel();
        panelAdministrar_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAdministrar_contenido = new javax.swing.JPanel();
        btn_editoriales = new javax.swing.JButton();
        btn_autores = new javax.swing.JButton();
        btn_libros = new javax.swing.JButton();
        btn_ejemplares = new javax.swing.JButton();
        btn_librosDigitales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_areasConocimiento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(687, 500));
        setPreferredSize(new java.awt.Dimension(687, 500));
        setLayout(new java.awt.GridLayout(1, 0));

        panelScrolleable.setHorizontalScrollBar(null);
        panelScrolleable.setMinimumSize(new java.awt.Dimension(687, 500));
        panelScrolleable.setPreferredSize(new java.awt.Dimension(687, 500));

        subpanel_scrolleable.setBackground(new java.awt.Color(204, 204, 204));
        subpanel_scrolleable.setLayout(new java.awt.BorderLayout());

        panelAdministrar_titulo.setBackground(new java.awt.Color(204, 204, 204));
        panelAdministrar_titulo.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("San Francisco Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar");

        javax.swing.GroupLayout panelAdministrar_tituloLayout = new javax.swing.GroupLayout(panelAdministrar_titulo);
        panelAdministrar_titulo.setLayout(panelAdministrar_tituloLayout);
        panelAdministrar_tituloLayout.setHorizontalGroup(
            panelAdministrar_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        panelAdministrar_tituloLayout.setVerticalGroup(
            panelAdministrar_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        subpanel_scrolleable.add(panelAdministrar_titulo, java.awt.BorderLayout.PAGE_START);

        panelAdministrar_contenido.setMinimumSize(new java.awt.Dimension(687, 500));
        panelAdministrar_contenido.setOpaque(false);
        panelAdministrar_contenido.setPreferredSize(new java.awt.Dimension(687, 500));

        btn_editoriales.setBackground(new java.awt.Color(255, 255, 255));
        btn_editoriales.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_editoriales.setForeground(new java.awt.Color(255, 255, 255));
        btn_editoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/store-alt_64px.png"))); // NOI18N
        btn_editoriales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editoriales.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_editoriales.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_editoriales.setPreferredSize(new java.awt.Dimension(120, 120));

        btn_autores.setBackground(new java.awt.Color(255, 255, 255));
        btn_autores.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_autores.setForeground(new java.awt.Color(255, 255, 255));
        btn_autores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userBlue_64px.png"))); // NOI18N
        btn_autores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_autores.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_autores.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_autores.setOpaque(true);
        btn_autores.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_autores.setVerifyInputWhenFocusTarget(false);

        btn_libros.setBackground(new java.awt.Color(255, 255, 255));
        btn_libros.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_libros.setForeground(new java.awt.Color(255, 255, 255));
        btn_libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_64px.png"))); // NOI18N
        btn_libros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_libros.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_libros.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_libros.setPreferredSize(new java.awt.Dimension(120, 120));

        btn_ejemplares.setBackground(new java.awt.Color(255, 255, 255));
        btn_ejemplares.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_ejemplares.setForeground(new java.awt.Color(255, 255, 255));
        btn_ejemplares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document_64px.png"))); // NOI18N
        btn_ejemplares.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ejemplares.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_ejemplares.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_ejemplares.setPreferredSize(new java.awt.Dimension(120, 120));

        btn_librosDigitales.setBackground(new java.awt.Color(255, 255, 255));
        btn_librosDigitales.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_librosDigitales.setForeground(new java.awt.Color(255, 255, 255));
        btn_librosDigitales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/documentLine_px.png"))); // NOI18N
        btn_librosDigitales.setToolTipText("");
        btn_librosDigitales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_librosDigitales.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_librosDigitales.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_librosDigitales.setOpaque(true);
        btn_librosDigitales.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_librosDigitales.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editoriales");

        jLabel4.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Autores");

        jLabel6.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Libros");

        jLabel7.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ejemplares");

        jLabel8.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Libros Digitales");

        btn_areasConocimiento.setBackground(new java.awt.Color(255, 255, 255));
        btn_areasConocimiento.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_areasConocimiento.setForeground(new java.awt.Color(255, 255, 255));
        btn_areasConocimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation-cap_64px.png"))); // NOI18N
        btn_areasConocimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_areasConocimiento.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_areasConocimiento.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_areasConocimiento.setOpaque(true);
        btn_areasConocimiento.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_areasConocimiento.setVerifyInputWhenFocusTarget(false);

        jLabel5.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Areas Conocimiento");

        javax.swing.GroupLayout panelAdministrar_contenidoLayout = new javax.swing.GroupLayout(panelAdministrar_contenido);
        panelAdministrar_contenido.setLayout(panelAdministrar_contenidoLayout);
        panelAdministrar_contenidoLayout.setHorizontalGroup(
            panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_editoriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_ejemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_autores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_areasConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_librosDigitales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelAdministrar_contenidoLayout.setVerticalGroup(
            panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdministrar_contenidoLayout.createSequentialGroup()
                            .addComponent(btn_autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdministrar_contenidoLayout.createSequentialGroup()
                            .addComponent(btn_areasConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)))
                    .addComponent(btn_editoriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ejemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_librosDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        subpanel_scrolleable.add(panelAdministrar_contenido, java.awt.BorderLayout.CENTER);

        panelScrolleable.setViewportView(subpanel_scrolleable);

        add(panelScrolleable);
    }// </editor-fold>//GEN-END:initComponents

    
    // ------------------ LISTENERS ------------------    
    public void addListenerEditoriales(ActionListener listener){
        btn_editoriales.addActionListener(listener);
    }

    public void addListenerAutores(ActionListener listener){
        btn_autores.addActionListener(listener);
    }
    
    public void addListenerLibros(ActionListener listener){
        btn_libros.addActionListener(listener);
    }
    
    public void addListenerEjemplares(ActionListener listener){
        btn_ejemplares.addActionListener(listener);
    }
    
    public void addListenerLibrosDigitales(ActionListener listener){
        btn_librosDigitales.addActionListener(listener);
    }
    
    public void addListenerAreasConocimiento(ActionListener listener){
        btn_areasConocimiento.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_areasConocimiento;
    private javax.swing.JButton btn_autores;
    private javax.swing.JButton btn_editoriales;
    private javax.swing.JButton btn_ejemplares;
    private javax.swing.JButton btn_libros;
    private javax.swing.JButton btn_librosDigitales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelAdministrar_contenido;
    private javax.swing.JPanel panelAdministrar_titulo;
    private javax.swing.JScrollPane panelScrolleable;
    private javax.swing.JPanel subpanel_scrolleable;
    // End of variables declaration//GEN-END:variables

}
