package Paneles;

import java.awt.event.ActionListener;

/**
 * Bases de datos 750006C-01
 * Proyecto de curso
 * Profesor: Oswaldo Solarte
 * 
 * Archivo: PanelAdministrar.java
 * Licencia: GNU-GPL
 * @version 1.0
 * 
 * @author Alejandro Guerrero Cano      (202179652-3743) {@literal <"alejandro.cano@correounivalle.edu.co">} 
 * @author Juan David Loaiza Santiago   (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">} 
 * @author Juan Sebastian Muñoz Rojas   (202177436-3743) {@literal <"juan.munoz.rojas@correounivalle.edu.co">} 
 * 
 */

public class PanelAvanzado extends javax.swing.JPanel {

    /** Creates new form PanelAdministrar */
    public PanelAvanzado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrolleable = new javax.swing.JScrollPane();
        subpanel_scrolleable = new javax.swing.JPanel();
        panelAdministrar_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAdministrar_contenido = new javax.swing.JPanel();
        lbl_usuarios = new javax.swing.JLabel();
        btn_usuarios = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        lbl_empleados = new javax.swing.JLabel();
        btn_cambiarContrasena = new javax.swing.JButton();
        lbl_cambiarPassword = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(687, 500));
        setPreferredSize(new java.awt.Dimension(687, 500));
        setLayout(new java.awt.GridLayout(1, 0));

        panelScrolleable.setHorizontalScrollBar(null);
        panelScrolleable.setMinimumSize(new java.awt.Dimension(687, 500));
        panelScrolleable.setPreferredSize(new java.awt.Dimension(687, 500));

        subpanel_scrolleable.setBackground(new java.awt.Color(204, 204, 204));
        subpanel_scrolleable.setLayout(new java.awt.BorderLayout());

        panelAdministrar_titulo.setBackground(new java.awt.Color(204, 204, 204));
        panelAdministrar_titulo.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("San Francisco Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Avanzado");

        javax.swing.GroupLayout panelAdministrar_tituloLayout = new javax.swing.GroupLayout(panelAdministrar_titulo);
        panelAdministrar_titulo.setLayout(panelAdministrar_tituloLayout);
        panelAdministrar_tituloLayout.setHorizontalGroup(
            panelAdministrar_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        panelAdministrar_tituloLayout.setVerticalGroup(
            panelAdministrar_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        subpanel_scrolleable.add(panelAdministrar_titulo, java.awt.BorderLayout.PAGE_START);

        panelAdministrar_contenido.setMinimumSize(new java.awt.Dimension(687, 500));
        panelAdministrar_contenido.setOpaque(false);
        panelAdministrar_contenido.setPreferredSize(new java.awt.Dimension(687, 500));

        lbl_usuarios.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        lbl_usuarios.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_usuarios.setText("Gestionar usuarios");

        btn_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        btn_usuarios.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userBlue_64px.png"))); // NOI18N
        btn_usuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_usuarios.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_usuarios.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_usuarios.setOpaque(true);
        btn_usuarios.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_usuarios.setVerifyInputWhenFocusTarget(false);

        btn_empleados.setBackground(new java.awt.Color(255, 255, 255));
        btn_empleados.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_empleados.setForeground(new java.awt.Color(255, 255, 255));
        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userBlue_64px.png"))); // NOI18N
        btn_empleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_empleados.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_empleados.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_empleados.setOpaque(true);
        btn_empleados.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_empleados.setVerifyInputWhenFocusTarget(false);

        lbl_empleados.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        lbl_empleados.setForeground(new java.awt.Color(0, 0, 0));
        lbl_empleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empleados.setText("Gestionar empleados");

        btn_cambiarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        btn_cambiarContrasena.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_cambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btn_cambiarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_64px.png"))); // NOI18N
        btn_cambiarContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cambiarContrasena.setMaximumSize(new java.awt.Dimension(120, 120));
        btn_cambiarContrasena.setMinimumSize(new java.awt.Dimension(120, 120));
        btn_cambiarContrasena.setOpaque(true);
        btn_cambiarContrasena.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_cambiarContrasena.setVerifyInputWhenFocusTarget(false);

        lbl_cambiarPassword.setFont(new java.awt.Font("San Francisco Text", 1, 14)); // NOI18N
        lbl_cambiarPassword.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cambiarPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cambiarPassword.setText("Cambiar contraseña");

        javax.swing.GroupLayout panelAdministrar_contenidoLayout = new javax.swing.GroupLayout(panelAdministrar_contenido);
        panelAdministrar_contenido.setLayout(panelAdministrar_contenidoLayout);
        panelAdministrar_contenidoLayout.setHorizontalGroup(
            panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_empleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cambiarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cambiarPassword))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelAdministrar_contenidoLayout.setVerticalGroup(
            panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                        .addComponent(btn_cambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_cambiarPassword))
                    .addGroup(panelAdministrar_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                            .addComponent(btn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_empleados))
                        .addGroup(panelAdministrar_contenidoLayout.createSequentialGroup()
                            .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_usuarios))))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        subpanel_scrolleable.add(panelAdministrar_contenido, java.awt.BorderLayout.CENTER);

        panelScrolleable.setViewportView(subpanel_scrolleable);

        add(panelScrolleable);
    }// </editor-fold>//GEN-END:initComponents

    
    // ------------------ MODOS ------------------
    public void habilitarVerEmpleados(){
        btn_empleados.setVisible(true);
        lbl_empleados.setVisible(true);
    }
    
    public void deshabilitarVerEmpleados(){
        btn_empleados.setVisible(false);
        lbl_empleados.setVisible(false);
    }
    
    
    // ------------------ LISTENERS ------------------
    public void addListenerUsuarios(ActionListener listener){
        btn_usuarios.addActionListener(listener);
    }
    
    public void addListenerEmpleados(ActionListener listener){
        btn_empleados.addActionListener(listener);
    }
    
    public void addListenerCambiarContrasena(ActionListener listener){
        btn_cambiarContrasena.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiarContrasena;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cambiarPassword;
    private javax.swing.JLabel lbl_empleados;
    private javax.swing.JLabel lbl_usuarios;
    private javax.swing.JPanel panelAdministrar_contenido;
    private javax.swing.JPanel panelAdministrar_titulo;
    private javax.swing.JScrollPane panelScrolleable;
    private javax.swing.JPanel subpanel_scrolleable;
    // End of variables declaration//GEN-END:variables

}
