package Paneles;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */



import java.awt.event.ActionListener;

/**
 * 
 * Archivo: PanelLogin.java
 * Licencia: GNU-GPL
 * @version 1.0
 * 
 * @author Juan David Loaiza Santiago   (202177570-3743) {@literal <"juan.loaiza.santiago@correounivalle.edu.co">} 
 * 
 */


/**
 * Este objeto se creo como un objeto de tipo JPane Form por lo que puede ser importado en un objeto de JFrameForm
 * @author ihuntgore
 */

public class PanelRegistrarse extends javax.swing.JPanel{

    /** Creates new form VistaLogin */
    public PanelRegistrarse() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_tipo = new javax.swing.JLabel();
        box_tipoUsuario = new javax.swing.JComboBox<>();
        lbl_bar6 = new javax.swing.JLabel();
        lbl_usuarioAtrib1 = new javax.swing.JLabel();
        txtf_usuarioAtrib1 = new javax.swing.JTextField();
        lbl_usuarioAtrib2 = new javax.swing.JLabel();
        txtf_usuarioAtrib2 = new javax.swing.JTextField();
        lbl_bar7 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_correo = new javax.swing.JLabel();
        txtf_correo = new javax.swing.JTextField();
        lbl_bar1 = new javax.swing.JLabel();
        lbl_contrasena = new javax.swing.JLabel();
        txtf_contrasena = new javax.swing.JTextField();
        lbl_bar2 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txtf_nombre = new javax.swing.JTextField();
        lbl_bar3 = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        txtf_direccion = new javax.swing.JTextField();
        lbl_bar4 = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        txtf_telefono = new javax.swing.JTextField();
        lbl_bar5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("San Francisco Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrarse");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        lbl_tipo.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tipo.setText("Tipo: *");

        box_tipoUsuario.setBackground(new java.awt.Color(0, 102, 102));
        box_tipoUsuario.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        box_tipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        box_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor" }));
        box_tipoUsuario.setBorder(null);

        lbl_bar6.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar6.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar6.setText("jLabel4");
        lbl_bar6.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar6.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar6.setOpaque(true);
        lbl_bar6.setPreferredSize(new java.awt.Dimension(703, 20));

        lbl_usuarioAtrib1.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_usuarioAtrib1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usuarioAtrib1.setText("Carrera: *");

        txtf_usuarioAtrib1.setBackground(new java.awt.Color(255, 255, 255));
        txtf_usuarioAtrib1.setBorder(null);
        txtf_usuarioAtrib1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_usuarioAtrib2.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_usuarioAtrib2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usuarioAtrib2.setText("Universidad: *");

        txtf_usuarioAtrib2.setBackground(new java.awt.Color(255, 255, 255));
        txtf_usuarioAtrib2.setBorder(null);
        txtf_usuarioAtrib2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar7.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar7.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar7.setText("jLabel4");
        lbl_bar7.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar7.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar7.setOpaque(true);
        lbl_bar7.setPreferredSize(new java.awt.Dimension(703, 20));

        btn_registrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_registrar.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.setMaximumSize(new java.awt.Dimension(121, 26));
        btn_registrar.setMinimumSize(new java.awt.Dimension(121, 26));
        btn_registrar.setPreferredSize(new java.awt.Dimension(121, 26));

        btn_volver.setBackground(new java.awt.Color(0, 102, 102));
        btn_volver.setFont(new java.awt.Font("San Francisco Text", 1, 16)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.setMaximumSize(new java.awt.Dimension(121, 26));
        btn_volver.setMinimumSize(new java.awt.Dimension(121, 26));
        btn_volver.setPreferredSize(new java.awt.Dimension(121, 26));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuarioAtrib2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_bar6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_bar7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtf_usuarioAtrib2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tipo)
                            .addComponent(box_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuarioAtrib1)
                            .addComponent(txtf_usuarioAtrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lbl_usuarioAtrib1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_usuarioAtrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_usuarioAtrib2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_usuarioAtrib2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));

        lbl_correo.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_correo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_correo.setText("Correo: *");

        txtf_correo.setBackground(new java.awt.Color(255, 255, 255));
        txtf_correo.setBorder(null);
        txtf_correo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar1.setText("jLabel4");
        lbl_bar1.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar1.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar1.setOpaque(true);
        lbl_bar1.setPreferredSize(new java.awt.Dimension(703, 20));

        lbl_contrasena.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_contrasena.setForeground(new java.awt.Color(0, 0, 0));
        lbl_contrasena.setText("Contraseña: *");

        txtf_contrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtf_contrasena.setBorder(null);
        txtf_contrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar2.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar2.setText("jLabel4");
        lbl_bar2.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar2.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar2.setOpaque(true);
        lbl_bar2.setPreferredSize(new java.awt.Dimension(703, 20));

        lbl_nombre.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setText("Nombre: *");

        txtf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txtf_nombre.setBorder(null);
        txtf_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar3.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar3.setText("jLabel4");
        lbl_bar3.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar3.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar3.setOpaque(true);
        lbl_bar3.setPreferredSize(new java.awt.Dimension(703, 20));

        lbl_direccion.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_direccion.setForeground(new java.awt.Color(0, 0, 0));
        lbl_direccion.setText("Direccion: *");

        txtf_direccion.setBackground(new java.awt.Color(255, 255, 255));
        txtf_direccion.setBorder(null);
        txtf_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar4.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar4.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar4.setText("jLabel4");
        lbl_bar4.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar4.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar4.setOpaque(true);
        lbl_bar4.setPreferredSize(new java.awt.Dimension(703, 20));

        lbl_telefono.setFont(new java.awt.Font("San Francisco Text", 1, 18)); // NOI18N
        lbl_telefono.setForeground(new java.awt.Color(0, 0, 0));
        lbl_telefono.setText("Telefono: *");

        txtf_telefono.setBackground(new java.awt.Color(255, 255, 255));
        txtf_telefono.setBorder(null);
        txtf_telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_bar5.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bar5.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bar5.setText("jLabel4");
        lbl_bar5.setMaximumSize(new java.awt.Dimension(703, 20));
        lbl_bar5.setMinimumSize(new java.awt.Dimension(703, 20));
        lbl_bar5.setOpaque(true);
        lbl_bar5.setPreferredSize(new java.awt.Dimension(703, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_bar5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_telefono)
                    .addComponent(lbl_bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_direccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_direccion)
                    .addComponent(lbl_bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_nombre)
                    .addComponent(lbl_bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_contrasena)
                    .addComponent(lbl_bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_correo)
                        .addGap(263, 263, 263))
                    .addComponent(txtf_correo))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_contrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bar5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public void addActionRegistrar(ActionListener listener){
        btn_registrar.addActionListener(listener);
    }
    
    public void addActionVolver(ActionListener listener){
        btn_volver.addActionListener(listener);
    }
    
    public void addActionBoxTipoUsuario(ActionListener listener){
        box_tipoUsuario.addActionListener(listener);
    }
    
    public void setAtributosEstudiante(){
        lbl_usuarioAtrib1.setText("Carrera: *");
        lbl_usuarioAtrib2.setText("Universidad: *");
    }
    
    public void setAtributosProfesor(){
        lbl_usuarioAtrib1.setText("Titulo: *");
        lbl_usuarioAtrib2.setText("Dependencia: *");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_tipoUsuario;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_bar1;
    private javax.swing.JLabel lbl_bar2;
    private javax.swing.JLabel lbl_bar3;
    private javax.swing.JLabel lbl_bar4;
    private javax.swing.JLabel lbl_bar5;
    private javax.swing.JLabel lbl_bar6;
    private javax.swing.JLabel lbl_bar7;
    private javax.swing.JLabel lbl_contrasena;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_usuarioAtrib1;
    private javax.swing.JLabel lbl_usuarioAtrib2;
    private javax.swing.JTextField txtf_contrasena;
    private javax.swing.JTextField txtf_correo;
    private javax.swing.JTextField txtf_direccion;
    private javax.swing.JTextField txtf_nombre;
    private javax.swing.JTextField txtf_telefono;
    private javax.swing.JTextField txtf_usuarioAtrib1;
    private javax.swing.JTextField txtf_usuarioAtrib2;
    // End of variables declaration//GEN-END:variables

}
